[project]
name = "osagent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-dotenv>=1.0.0",
    "langchain>=1.2.12",
    "langchain-ollama>=1.0.1",
    "pygithub>=2.8.1",
    "pydantic>=2.12.5",
    "langchain-anthropic>=1.4.0",
]

[tool.pytest.ini_options]
  env = [
      "GITHUB_TOKEN=dummy"
  ]